/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author derhe
 */
public class ImprimirFactura extends javax.swing.JFrame {

    /**
     * Creates new form ImprimirFactura
     */
    public ImprimirFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroFactura = new javax.swing.JLabel();
        jLabelNombreEmpresa = new javax.swing.JLabel();
        jLabelFechaFactura = new javax.swing.JLabel();
        jLabelDatosCliente = new javax.swing.JLabel();
        jLabelNombreCliente = new javax.swing.JLabel();
        jLabelApellidoCliente = new javax.swing.JLabel();
        jLabelTelefonoCliente = new javax.swing.JLabel();
        jLabelListaProducto = new javax.swing.JLabel();
        jLabelNombreProducto = new javax.swing.JLabel();
        jLabelCantidadProducto = new javax.swing.JLabel();
        jLabelSubTotal = new javax.swing.JLabel();
        jButtonGuardarProducto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabelValorProducto = new javax.swing.JLabel();
        jLabelCodigoProducto = new javax.swing.JLabel();
        jTextFieldNumeroFactura = new javax.swing.JTextField();
        jTextFieldFechaFactura = new javax.swing.JTextField();
        jPanelListaProductos = new javax.swing.JPanel();
        jTextFieldIdProducto1 = new javax.swing.JTextField();
        jTextFieldNombreProducto1 = new javax.swing.JTextField();
        jTextFieldCantidadProducto1 = new javax.swing.JTextField();
        jTextFieldValorProducto1 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto1 = new javax.swing.JTextField();
        jTextFieldIdProducto2 = new javax.swing.JTextField();
        jTextFieldNombreProducto2 = new javax.swing.JTextField();
        jTextFieldCantidadProducto2 = new javax.swing.JTextField();
        jTextFieldValorProducto2 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto2 = new javax.swing.JTextField();
        jTextFieldNombreProducto3 = new javax.swing.JTextField();
        jTextFieldIdProducto3 = new javax.swing.JTextField();
        jTextFieldCantidadProducto3 = new javax.swing.JTextField();
        jTextFieldValorProducto3 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto3 = new javax.swing.JTextField();
        jTextFieldCantidadProducto4 = new javax.swing.JTextField();
        jTextFieldIdProducto4 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto4 = new javax.swing.JTextField();
        jTextFieldNombreProducto4 = new javax.swing.JTextField();
        jTextFieldValorProducto4 = new javax.swing.JTextField();
        jTextFieldNombreProducto5 = new javax.swing.JTextField();
        jTextFieldCantidadProducto5 = new javax.swing.JTextField();
        jTextFieldValorProducto5 = new javax.swing.JTextField();
        jTextFieldIdProducto5 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto5 = new javax.swing.JTextField();
        jTextFieldNombreProducto6 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto6 = new javax.swing.JTextField();
        jTextFieldIdProducto6 = new javax.swing.JTextField();
        jTextFieldCantidadProducto6 = new javax.swing.JTextField();
        jTextFieldValorProducto6 = new javax.swing.JTextField();
        jTextFieldCantidadProducto7 = new javax.swing.JTextField();
        jTextFieldValorProducto7 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto7 = new javax.swing.JTextField();
        jTextFieldIdProducto7 = new javax.swing.JTextField();
        jTextFieldNombreProducto7 = new javax.swing.JTextField();
        jTextFieldNombreProducto8 = new javax.swing.JTextField();
        jTextFieldIdProducto8 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto8 = new javax.swing.JTextField();
        jTextFieldValorProducto8 = new javax.swing.JTextField();
        jTextFieldCantidadProducto8 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto9 = new javax.swing.JTextField();
        jTextFieldCantidadProducto9 = new javax.swing.JTextField();
        jTextFieldIdProducto9 = new javax.swing.JTextField();
        jTextFieldNombreProducto9 = new javax.swing.JTextField();
        jTextFieldValorProducto9 = new javax.swing.JTextField();
        jTextFieldIdProducto10 = new javax.swing.JTextField();
        jTextFieldValorProducto10 = new javax.swing.JTextField();
        jTextFieldNombreProducto10 = new javax.swing.JTextField();
        jTextFieldCantidadProducto10 = new javax.swing.JTextField();
        jTextFieldSubTotalProducto10 = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jTextFieldApellidoCliente = new javax.swing.JTextField();
        jTextFieldTelefonCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNumeroFactura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNumeroFactura.setText("Numero Factura:");

        jLabelNombreEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombreEmpresa.setForeground(new java.awt.Color(0, 51, 102));
        jLabelNombreEmpresa.setText("INVERSIONES CICLO 2 JAVA");

        jLabelFechaFactura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFechaFactura.setText("Fecha Factura:");

        jLabelDatosCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDatosCliente.setForeground(new java.awt.Color(0, 51, 102));
        jLabelDatosCliente.setText("Datos del cliente");

        jLabelNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNombreCliente.setText("Nombre:");

        jLabelApellidoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelApellidoCliente.setText("Apellido:");

        jLabelTelefonoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTelefonoCliente.setText("Telefono:");

        jLabelListaProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelListaProducto.setForeground(new java.awt.Color(0, 51, 102));
        jLabelListaProducto.setText("Lista de Producto");

        jLabelNombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNombreProducto.setText("Nombre:");

        jLabelCantidadProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCantidadProducto.setText("Cantidad");

        jLabelSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSubTotal.setText("SubTotal:");

        jButtonGuardarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGuardarProducto.setText("Regresar");
        jButtonGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarProductoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Total Factura:");

        jLabelValorProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorProducto.setText("Valor Unitario:");
        jLabelValorProducto.setToolTipText("");

        jLabelCodigoProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigoProducto.setText("Código:");

        jTextFieldNumeroFactura.setEditable(false);

        jTextFieldFechaFactura.setEditable(false);

        jTextFieldIdProducto1.setEditable(false);
        jTextFieldIdProducto1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldNombreProducto1.setEditable(false);

        jTextFieldCantidadProducto1.setEditable(false);

        jTextFieldValorProducto1.setEditable(false);

        jTextFieldSubTotalProducto1.setEditable(false);

        jTextFieldIdProducto2.setEditable(false);
        jTextFieldIdProducto2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldNombreProducto2.setEditable(false);

        jTextFieldCantidadProducto2.setEditable(false);

        jTextFieldValorProducto2.setEditable(false);

        jTextFieldSubTotalProducto2.setEditable(false);

        jTextFieldNombreProducto3.setEditable(false);

        jTextFieldIdProducto3.setEditable(false);
        jTextFieldIdProducto3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldCantidadProducto3.setEditable(false);

        jTextFieldValorProducto3.setEditable(false);

        jTextFieldSubTotalProducto3.setEditable(false);

        jTextFieldCantidadProducto4.setEditable(false);

        jTextFieldIdProducto4.setEditable(false);
        jTextFieldIdProducto4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldSubTotalProducto4.setEditable(false);

        jTextFieldNombreProducto4.setEditable(false);

        jTextFieldValorProducto4.setEditable(false);

        jTextFieldNombreProducto5.setEditable(false);

        jTextFieldCantidadProducto5.setEditable(false);

        jTextFieldValorProducto5.setEditable(false);

        jTextFieldIdProducto5.setEditable(false);
        jTextFieldIdProducto5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldSubTotalProducto5.setEditable(false);

        jTextFieldNombreProducto6.setEditable(false);

        jTextFieldSubTotalProducto6.setEditable(false);

        jTextFieldIdProducto6.setEditable(false);
        jTextFieldIdProducto6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldCantidadProducto6.setEditable(false);

        jTextFieldValorProducto6.setEditable(false);

        jTextFieldCantidadProducto7.setEditable(false);

        jTextFieldValorProducto7.setEditable(false);

        jTextFieldSubTotalProducto7.setEditable(false);

        jTextFieldIdProducto7.setEditable(false);
        jTextFieldIdProducto7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldNombreProducto7.setEditable(false);

        jTextFieldNombreProducto8.setEditable(false);

        jTextFieldIdProducto8.setEditable(false);
        jTextFieldIdProducto8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldSubTotalProducto8.setEditable(false);

        jTextFieldValorProducto8.setEditable(false);

        jTextFieldCantidadProducto8.setEditable(false);

        jTextFieldSubTotalProducto9.setEditable(false);

        jTextFieldCantidadProducto9.setEditable(false);

        jTextFieldIdProducto9.setEditable(false);
        jTextFieldIdProducto9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldNombreProducto9.setEditable(false);

        jTextFieldValorProducto9.setEditable(false);

        jTextFieldIdProducto10.setEditable(false);
        jTextFieldIdProducto10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldValorProducto10.setEditable(false);

        jTextFieldNombreProducto10.setEditable(false);

        jTextFieldCantidadProducto10.setEditable(false);

        jTextFieldSubTotalProducto10.setEditable(false);

        javax.swing.GroupLayout jPanelListaProductosLayout = new javax.swing.GroupLayout(jPanelListaProductos);
        jPanelListaProductos.setLayout(jPanelListaProductosLayout);
        jPanelListaProductosLayout.setHorizontalGroup(
            jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto1))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto5, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto6, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto7, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto8, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto9, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addComponent(jTextFieldIdProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNombreProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCantidadProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldValorProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSubTotalProducto10, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelListaProductosLayout.setVerticalGroup(
            jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantidadProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSubTotalProducto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldTotal.setEditable(false);

        jTextFieldNombreCliente.setEditable(false);

        jTextFieldApellidoCliente.setEditable(false);

        jTextFieldTelefonCliente.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelListaProducto)
                                    .addComponent(jLabelDatosCliente))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabelCodigoProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCantidadProducto)
                                .addGap(31, 31, 31)
                                .addComponent(jLabelValorProducto)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelSubTotal)))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFechaFactura)
                            .addComponent(jLabelNombreEmpresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabelNombreCliente)
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelApellidoCliente)
                                            .addGap(19, 19, 19)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTelefonoCliente)
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldTelefonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabelNombreProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelNumeroFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButtonGuardarProducto)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreEmpresa)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaFactura)
                    .addComponent(jLabelNumeroFactura)
                    .addComponent(jTextFieldNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDatosCliente)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCliente)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidoCliente)
                    .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefonoCliente)
                    .addComponent(jTextFieldTelefonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabelListaProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreProducto)
                    .addComponent(jLabelCantidadProducto)
                    .addComponent(jLabelValorProducto)
                    .addComponent(jLabelSubTotal)
                    .addComponent(jLabelCodigoProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardarProducto)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarProductoActionPerformed
            // TODO add your handling code here:
             SistemaFacturacionView crearFactura = new SistemaFacturacionView();
            crearFactura.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonGuardarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirFactura().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarProducto;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabelApellidoCliente;
    private javax.swing.JLabel jLabelCantidadProducto;
    private javax.swing.JLabel jLabelCodigoProducto;
    private javax.swing.JLabel jLabelDatosCliente;
    private javax.swing.JLabel jLabelFechaFactura;
    private javax.swing.JLabel jLabelListaProducto;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelNombreEmpresa;
    private javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JLabel jLabelNumeroFactura;
    private javax.swing.JLabel jLabelSubTotal;
    private javax.swing.JLabel jLabelTelefonoCliente;
    private javax.swing.JLabel jLabelValorProducto;
    private javax.swing.JPanel jPanelListaProductos;
    public javax.swing.JTextField jTextFieldApellidoCliente;
    public javax.swing.JTextField jTextFieldCantidadProducto1;
    public javax.swing.JTextField jTextFieldCantidadProducto10;
    public javax.swing.JTextField jTextFieldCantidadProducto2;
    public javax.swing.JTextField jTextFieldCantidadProducto3;
    public javax.swing.JTextField jTextFieldCantidadProducto4;
    public javax.swing.JTextField jTextFieldCantidadProducto5;
    public javax.swing.JTextField jTextFieldCantidadProducto6;
    public javax.swing.JTextField jTextFieldCantidadProducto7;
    public javax.swing.JTextField jTextFieldCantidadProducto8;
    public javax.swing.JTextField jTextFieldCantidadProducto9;
    public javax.swing.JTextField jTextFieldFechaFactura;
    public javax.swing.JTextField jTextFieldIdProducto1;
    public javax.swing.JTextField jTextFieldIdProducto10;
    public javax.swing.JTextField jTextFieldIdProducto2;
    public javax.swing.JTextField jTextFieldIdProducto3;
    public javax.swing.JTextField jTextFieldIdProducto4;
    public javax.swing.JTextField jTextFieldIdProducto5;
    public javax.swing.JTextField jTextFieldIdProducto6;
    public javax.swing.JTextField jTextFieldIdProducto7;
    public javax.swing.JTextField jTextFieldIdProducto8;
    public javax.swing.JTextField jTextFieldIdProducto9;
    public javax.swing.JTextField jTextFieldNombreCliente;
    public javax.swing.JTextField jTextFieldNombreProducto1;
    public javax.swing.JTextField jTextFieldNombreProducto10;
    public javax.swing.JTextField jTextFieldNombreProducto2;
    public javax.swing.JTextField jTextFieldNombreProducto3;
    public javax.swing.JTextField jTextFieldNombreProducto4;
    public javax.swing.JTextField jTextFieldNombreProducto5;
    public javax.swing.JTextField jTextFieldNombreProducto6;
    public javax.swing.JTextField jTextFieldNombreProducto7;
    public javax.swing.JTextField jTextFieldNombreProducto8;
    public javax.swing.JTextField jTextFieldNombreProducto9;
    public javax.swing.JTextField jTextFieldNumeroFactura;
    public javax.swing.JTextField jTextFieldSubTotalProducto1;
    public javax.swing.JTextField jTextFieldSubTotalProducto10;
    public javax.swing.JTextField jTextFieldSubTotalProducto2;
    public javax.swing.JTextField jTextFieldSubTotalProducto3;
    public javax.swing.JTextField jTextFieldSubTotalProducto4;
    public javax.swing.JTextField jTextFieldSubTotalProducto5;
    public javax.swing.JTextField jTextFieldSubTotalProducto6;
    public javax.swing.JTextField jTextFieldSubTotalProducto7;
    public javax.swing.JTextField jTextFieldSubTotalProducto8;
    public javax.swing.JTextField jTextFieldSubTotalProducto9;
    public javax.swing.JTextField jTextFieldTelefonCliente;
    public javax.swing.JTextField jTextFieldTotal;
    public javax.swing.JTextField jTextFieldValorProducto1;
    public javax.swing.JTextField jTextFieldValorProducto10;
    public javax.swing.JTextField jTextFieldValorProducto2;
    public javax.swing.JTextField jTextFieldValorProducto3;
    public javax.swing.JTextField jTextFieldValorProducto4;
    public javax.swing.JTextField jTextFieldValorProducto5;
    public javax.swing.JTextField jTextFieldValorProducto6;
    public javax.swing.JTextField jTextFieldValorProducto7;
    public javax.swing.JTextField jTextFieldValorProducto8;
    public javax.swing.JTextField jTextFieldValorProducto9;
    // End of variables declaration//GEN-END:variables
}
